### ISSUE TITLE
Getting error "Received invalid packet type/version from client"

### ISSUE THREAD

**Issue by bhavinajmera** [djmitche/pynsca#16]
Hi,
I am using NSCA 2.9.1 with pynsca 1.5 I am getting an error Received invalid packet type/version from client - possibly due to client using wrong password or crypto algorithm?, but when i use it with send_nsca client library it works fine. My encryption mode is 1 (XOR). I am using NSCANotifier("nagios-server", password=None, encryption_mode=1) Kindly help me out.

**Comment by djmitche** [comment]
Well, without seeing your password I can't really tell if you're using the wrong password, but that would be my guess.

**Comment by bhavinajmera** [comment]
Thanks for the prompt reply, I am using 
notif = pynsca.NSCANotifier("192.168.100.1", encryption_mode=1, password=secret)
notif.svc_result(oc1, "nova-api", pynsca.OK, "delay-instance-creation: %f"%(runtime,))

and in nsca.cfg 
password=secret
decryption_method=1

**Comment by djmitche** [comment]
Sorry, I really don't know -- I haven't actually used this for years.

I think others are successfully using the XOR method, though, so my first
guess is something with your setup.  It may also be a problem with newer
versions of NSCA having changed the protocol?

Dustin

**Comment by jantman** [comment]
I haven't used this in a while either, but I know that my former employer still has it in production.

1. I do remember us having to change our encryption method to something that worked with pynsca. You may need to test various encryption methods like I did. If you really need me to, I can ask someone to find out what we were using.
2. In your first code sample, you say that you're using ``password=None``. In the second one, you say that you're using ``password=secret`` and that your ``nsca.cfg`` defines ``password=secret``. Your python is setting the password to a variable named ``secret``, not the string "secret"; have you defined that variable correctly?
3. Can you please paste the actual code you're running, and the output of it? You said that you're getting an error, ``Received invalid packet type/version from client - possibly due to client using wrong password or crypto algorithm?``

The current master branch of nsca is still [checking](https://github.com/NagiosEnterprises/nsca/blob/master/src/nsca.c#L1133) for [protocol version "3"](https://github.com/NagiosEnterprises/nsca/blob/master/include/common.h#L109) which is the same as [what pynsca is sending](https://github.com/djmitche/pynsca/blob/master/pynsca.py#L46), so as long as you're using the official nsca binary, the protocol version isn't the problem.

**Comment by bhavinajmera** [comment]
Thanks for your help, It was my mistake in openstack nova python file modified it. It works now. Thanks for your help.
